SELECT 
		[Company_Name] AS [Company Name]
      ,[Transaction_Name_URL] AS [Transaction Name URL]
      ,[City_Of_London] AS [City]
      ,[State]
      ,[Country]
      ,[Region]
      ,[Organization_Industries] 
      ,[Organization_Name_URL]
      ,[Funding_Type] AS [Funding Type]
      ,[Money_Raised] AS [Money Raised]
      ,[Money_Raised_Currency] AS [Money Raised Currency]
      ,[Money_Raised_Currency_in_USD] AS [Money Raised Currency in USD]
      ,[Announced_Date] AS [Announced Date]
  FROM [DA].[dbo].[Funding Rounds Data (Cleaned Data)]
